-- Create activity_logs table
CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  action TEXT NOT NULL,            -- 'create', 'update', 'delete', 'upload', 'import'
  entity_type TEXT NOT NULL,       -- 'project', 'file', 'complaint'
  entity_id TEXT,                  -- ID of the modified record
  entity_name TEXT,                -- Name/Title of the modified record
  details JSONB,                   -- Additional details (old_value, new_value)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- Create policies (Adjust based on your auth model, usually admins only)
CREATE POLICY "Allow read access for authenticated users" ON activity_logs
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow insert access for authenticated users" ON activity_logs
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');
