-- Migration: CMS Redesign
-- สร้างตารางใหม่สำหรับระบบ CMS เต็มรูปแบบ

-- ============================================
-- 1. Organizations Table
-- ============================================
CREATE TABLE organizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  short_name TEXT,
  type TEXT DEFAULT 'club' CHECK (type IN ('club', 'council', 'committee', 'department', 'other')),
  campus TEXT NOT NULL DEFAULT 'central' CHECK (campus IN ('central', 'rangsit', 'thaprachan', 'lampang')),
  contact_person TEXT,
  contact_email TEXT,
  description TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON organizations
  FOR SELECT USING (true);

CREATE POLICY "Allow full access for authenticated users" ON organizations
  FOR ALL USING (auth.role() = 'authenticated');

-- Index for common queries
CREATE INDEX idx_organizations_campus ON organizations(campus);
CREATE INDEX idx_organizations_type ON organizations(type);

-- ============================================
-- 2. Add organization_id FK to projects
-- ============================================
ALTER TABLE projects ADD COLUMN organization_id BIGINT REFERENCES organizations(id) ON DELETE SET NULL;

CREATE INDEX idx_projects_organization_id ON projects(organization_id);

-- Data migration: populate organizations from existing projects
INSERT INTO organizations (name, campus)
SELECT DISTINCT organization, campus
FROM projects
WHERE organization IS NOT NULL AND organization != ''
ON CONFLICT (name) DO NOTHING;

-- Link existing projects to their organizations
UPDATE projects p
SET organization_id = o.id
FROM organizations o
WHERE p.organization = o.name;

-- ============================================
-- 3. Import Batches Table
-- ============================================
CREATE TABLE import_batches (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_email TEXT NOT NULL,
  fiscal_year INTEGER NOT NULL,
  campus TEXT NOT NULL CHECK (campus IN ('central', 'rangsit', 'thaprachan', 'lampang')),
  source_type TEXT NOT NULL CHECK (source_type IN ('template_excel', 'template_csv', 'ai_pdf', 'manual')),
  file_name TEXT,
  total_rows INTEGER DEFAULT 0,
  imported_rows INTEGER DEFAULT 0,
  failed_rows INTEGER DEFAULT 0,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'validating', 'previewing', 'importing', 'completed', 'rolled_back', 'failed')),
  error_log JSONB,
  project_ids BIGINT[],
  created_at TIMESTAMPTZ DEFAULT now(),
  completed_at TIMESTAMPTZ
);

ALTER TABLE import_batches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow full access for authenticated users" ON import_batches
  FOR ALL USING (auth.role() = 'authenticated');

CREATE INDEX idx_import_batches_status ON import_batches(status);
CREATE INDEX idx_import_batches_created_at ON import_batches(created_at DESC);

-- ============================================
-- 4. Budget Categories Table
-- ============================================
CREATE TABLE budget_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  max_rate NUMERIC,
  unit TEXT,
  rules TEXT,
  campus TEXT DEFAULT 'central' CHECK (campus IN ('central', 'rangsit', 'thaprachan', 'lampang')),
  is_active BOOLEAN DEFAULT TRUE,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE budget_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON budget_categories
  FOR SELECT USING (true);

CREATE POLICY "Allow full access for authenticated users" ON budget_categories
  FOR ALL USING (auth.role() = 'authenticated');

-- ============================================
-- 5. CMS Pages Table
-- ============================================
CREATE TABLE cms_pages (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  updated_by TEXT,
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE cms_pages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON cms_pages
  FOR SELECT USING (true);

CREATE POLICY "Allow full access for authenticated users" ON cms_pages
  FOR ALL USING (auth.role() = 'authenticated');

-- Seed default pages
INSERT INTO cms_pages (id, title, content) VALUES
  ('about', 'เกี่ยวกับเรา', '# เกี่ยวกับ TU Open Data

แพลตฟอร์มเปิดเผยข้อมูลงบประมาณกิจกรรมนักศึกษา มหาวิทยาลัยธรรมศาสตร์'),
  ('api-docs', 'เอกสาร API', '# API Documentation

เอกสารสำหรับการเข้าถึงข้อมูลผ่าน API');

-- ============================================
-- 6. System Settings Table
-- ============================================
CREATE TABLE system_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  description TEXT,
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON system_settings
  FOR SELECT USING (true);

CREATE POLICY "Allow full access for authenticated users" ON system_settings
  FOR ALL USING (auth.role() = 'authenticated');

-- Seed default settings
INSERT INTO system_settings (key, value, description) VALUES
  ('current_fiscal_year', '2568', 'ปีงบประมาณปัจจุบัน (พ.ศ.)'),
  ('site_title', '"TU Open Data"', 'ชื่อเว็บไซต์'),
  ('max_import_rows', '500', 'จำนวนแถวสูงสุดที่นำเข้าได้ต่อครั้ง');
