-- Create complaints table
CREATE TABLE complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('correction', 'complaint')),
  description TEXT NOT NULL,
  contact_info TEXT, -- Optional
  file_paths TEXT[], -- Array of Supabase Storage paths
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'acknowledged', 'resolved', 'ignored')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;

-- Allow public insert (anyone can report)
CREATE POLICY "Allow public insert complaints" ON complaints
  FOR INSERT WITH CHECK (true);

-- Allow admin full access
CREATE POLICY "Allow full access complaints for authenticated users" ON complaints
  FOR ALL USING (auth.role() = 'authenticated');

-- Storage Bucket for Complaint Files (if not exists)
-- insert into storage.buckets (id, name, public) values ('complaint_files', 'complaint_files', true);
-- CREATE POLICY "Public Upload Complaints" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'complaint_files' );
-- CREATE POLICY "files_select_auth" ON storage.objects FOR SELECT USING ( bucket_id = 'complaint_files' AND auth.role() = 'authenticated' );
