-- Create projects table
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization TEXT NOT NULL,
  project_name TEXT NOT NULL,
  fiscal_year INTEGER NOT NULL,
  budget_requested NUMERIC NOT NULL,
  budget_approved NUMERIC NOT NULL,
  budget_average NUMERIC, -- Added for งบประมาณเฉลี่ย
  status TEXT GENERATED ALWAYS AS (
    CASE
      WHEN budget_approved = 0 THEN 'ไม่อนุมัติ'
      WHEN budget_approved < budget_requested THEN 'ตัดงบ'
      ELSE 'อนุมัติ'
    END
  ) STORED,
  notes TEXT,
  is_published BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Create policy to allow read access for everyone
CREATE POLICY "Allow public read access" ON projects
  FOR SELECT USING (true);

-- Create policy to allow full access for authenticated users (admins)
CREATE POLICY "Allow full access for authenticated users" ON projects
  FOR ALL USING (auth.role() = 'authenticated');
